user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
             Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36'
accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp, 
         image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7'
domain_name: 'sstmk.ru'
phone_pattern: '^(8|\+7)?(\(\d{3}\))?(\d){1,5}-(\d){1,3}-(\d){1,3}$'